# fly.toml app configuration file generated for wakana-frontend-v2 on 2026-08-12T21:42:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wakana-frontend-v2'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

  [build.args]
    VITE_PUBLIC_API_URL = 'https://api.wakana.io/api'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
