package models

import (
	"encoding/json"
	"strconv"
	"time"
)

type Invoice struct {
	ID             string            `json:"id" gorm:"primary_key"`
	UserID         string            `json:"user_id"`
	InvoiceID      string            `json:"invoice_id"`
	ClientID       string            `json:"client_id"`
	Origin         string            `json:"origin"`
	Destination    string            `json:"destination"`
	InvoiceSummary string            `json:"invoice_summary"`
	Heading        string            `json:"heading"`
	FinalMessage   string            `json:"final_message"`
	Tax            float64           `json:"tax"`
	ExcludeTax     bool              `json:"exclude_tax" gorm:"default:false"`
	LineItems      []InvoiceLineItem `json:"line_items" gorm:"serializer:json"`
	StartDate      time.Time         `json:"start_date" swaggertype:"string" format:"date" example:"2006-01-02 15:04:05.000"`
	EndDate        time.Time         `json:"end_date" swaggertype:"string" format:"date" example:"2006-01-02 15:04:05.000"`
	CreatedAt      CustomTime        `json:"created_at" gorm:"default:CURRENT_TIMESTAMP" swaggertype:"string" format:"date" example:"2006-01-02 15:04:05.000"`
	UpdatedAt      CustomTime        `json:"updated_at" gorm:"default:CURRENT_TIMESTAMP" swaggertype:"string" format:"date" example:"2006-01-02 15:04:05.000"`
	Client         Client            `json:"client"`
}

type NewInvoice struct {
	ClientID       string            `json:"client_id"`
	Origin         string            `json:"origin"`
	Destination    string            `json:"destination"`
	InvoiceSummary string            `json:"invoice_summary"`
	Heading        string            `json:"heading"`
	FinalMessage   string            `json:"final_message"`
	StartDate      CustomTime        `json:"start_date" swaggertype:"string" format:"date" example:"2006-01-02 15:04:05.000"`
	EndDate        CustomTime        `json:"end_date" swaggertype:"string" format:"date" example:"2006-01-02 15:04:05.000"`
	LineItems      []InvoiceLineItem `json:"line_items" gorm:"serializer:json"`
}

type InvoiceLineItem struct {
	Title         string `json:"title"`
	TotalSeconds  int64  `json:"total_seconds"`
	AutoGenerated bool   `json:"auto_generated"`
}

func (i *InvoiceLineItem) UnmarshalJSON(data []byte) error {
	type Alias InvoiceLineItem
	aux := &struct {
		TotalSeconds interface{} `json:"total_seconds"`
		*Alias
	}{
		Alias: (*Alias)(i),
	}

	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}

	if aux.TotalSeconds != nil {
		switch v := aux.TotalSeconds.(type) {
		case float64:
			i.TotalSeconds = int64(v)
		case string:
			val, err := strconv.ParseInt(v, 10, 64)
			if err != nil {
				return err
			}
			i.TotalSeconds = val
		default:
			i.TotalSeconds = 0
		}
	}

	return nil
}

type InvoiceUpdate struct {
	Origin         string            `json:"origin"`
	Tax            float64           `json:"tax"`
	ExcludeTax     *bool             `json:"exclude_tax"`
	Destination    string            `json:"destination"`
	InvoiceSummary *string           `json:"invoice_summary"`
	Heading        *string           `json:"heading"`
	FinalMessage   *string           `json:"final_message"`
	LineItems      []InvoiceLineItem `json:"line_items" gorm:"serializer:json"`
}

type NewInvoiceData struct {
	ClientID  string `json:"client_id"`
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

type NewlyGeneratedInvoiceData struct {
	StartDate time.Time         `json:"start_date"`
	EndDate   time.Time         `json:"end_date"`
	LineItems []InvoiceLineItem `json:"line_items"`
}
